# **INTRODUCCIÓN A ESTADÍSTICA INFERENCIAL**

Ejercicios de estadística inferencial aplicados con Python, incluyendo prueba de hipótesis, regresión lineal simple y descenso de gradiente.

## **PRUEBA DE HIPÓTESIS**

La **prueba de hipótesis** es un procedimiento formal dentro de la estadística inferencial que se usa para aceptar o rechazar una afirmación sobre un parámetro poblacional. Se basa en comparar dos hipótesis opuestas: la nula ($H_0$) y la alternativa ($H_1$).

***NOTA:*** *Se hará el uso de las bibliotecas de **Pandas**, **Seaborn** y **Scipy** para usar datasets precargados y operaciones estadísticas sin entrar a tanto detalle a las librerías mismas. Para ello, se explicará mas a detalle en el siguiente módulo.*

In [ ]:
# Importar librerías
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# Importar dataset
df_tips= sns.load_dataset('tips')
df_tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### **NIVEL DE SIGNIFICANCIA:**

Es el umbral de error que estamos dispuestos a aceptar. Comúnmente se utiliza **$\alpha = 0.01, 0.05, 0.1$** representando el 1%, 5%, y 10% de nivel de significancia correspondientemente.

* Si el **p-value < $\alpha$**: Rechazamos $H_0$ (Hay evidencia estadística).

* Si el **p-value > $\alpha$**: No podemos rechazar $H_0$ (No hay suficiente evidencia).

In [ ]:
# Importar módulo
from scipy import stats

**Caso práctico:** ¿Existe una diferencia significativa entre la propina que dan los fumadores vs. los no fumadores?

* $H_0$: La media de propinas es igual para ambos grupos.

* $H_1$: La media de propinas es distinta entre fumadores y no fumadores.

In [ ]:
# Separaración de grupos

propinas_fumadores = df_tips[df_tips['smoker'] == 'Yes']['tip']
propinas_no_fumadores = df_tips[df_tips['smoker'] == 'No']['tip']

In [ ]:
propinas_no_fumadores.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [ ]:
# Aplicar Prueba T de Student

t_statistic, p_value = stats.ttest_ind(propinas_fumadores, propinas_no_fumadores)

print(f"Estadístico T: {t_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

Estadístico T: 0.0922
P-Value: 0.9266

In [ ]:
# Interpretar resultados

if p_value < 0.01:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia muy significativa entre las propinas de ambos grupos.")
elif p_value >= 0.01 and p_value < 0.05:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia altamente significativa entre las propinas de ambos grupos.")
elif p_value >= 0.05 and p_value < 0.10:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia moderadamente significativa entre las propinas de ambos grupos.")
else:
    print("\nConclusión: No podemos rechazar la Hipótesis Nula.")
    print("No hay evidencia suficiente para decir que las propinas son diferentes.")

Conclusión: No podemos rechazar la Hipótesis Nula.
No hay evidencia suficiente para decir que las propinas son diferentes.

## **APRENDIZAJE ESTADÍSTICO**

El **aprendizaje estadístico** es un marco de trabajo que **combina la estadística y la computación** para construir **modelos predictivos o de clasificación** a partir de los datos. Es la base teórica de lo que hoy conocemos como Machine Learning.

### **REGRESIÓN LINEAL SIMPLE:**

Una **regresión lineal simple** es un método estadístico utilizado para modelar la relación entre una variable independiente, el cual actua como una **variable predictora**, y una variable dependiente que actua como una **variable objetivo**.

Su objetivo es encontrar una línea recta que mejor se ajuste a los datos para **predecir un valor objetivo en función del valor predictor**.

Una regresión lineal tiene la forma:

\begin{equation} \overline{y} = β\overline{x} + α  \, \, \, \equiv \, \, \, y = mx + b \end{equation}

Y su función de costo:

\begin{equation} c(x) = \frac{1}{n} Σ_{i=1}^n(\overline{y} - y_i)² \end{equation}

In [ ]:
df_tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# Definir regresión lineal

x= df_tips['total_bill']
y= df_tips['tip']

linear_regression = np.polyfit(x, y, 1)
beta, alpha = linear_regression

print(f'y = {beta:.3f} x + {alpha:.3f}')

y = 0.105 x + 0.920

In [ ]:
# Predicción de valores con regresión lineal
tb_pred_lr = int(input('Agrega el valor del total de la cuenta que deseas predecir la propina: '))
y_pred_lr = round(beta * tb_pred_lr + alpha, 2)

print(f'La propina será de {y_pred_lr}')

KeyboardInterrupt: Interrupted by user

In [ ]:
# Visualizar regresión lineal

plt.plot(x, y, 'o', color = 'red', label = 'Datos')
plt.plot(x, beta*x + alpha, color = 'blue', label = 'Regresión lineal')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.legend()
plt.grid()
plt.show()

In [ ]:
# Iterar pérdida de la regresión lineal

num_iteraciones = 100
perdida = []

for i in range(num_iteraciones):

    y_pred = np.polyval(linear_regression, x)
    error = ((y - y_pred) ** 2).mean()
    perdida.append(error)

In [ ]:
# Visualizar pérdida de la regresión lineal

plt.plot(perdida)
plt.xlabel('Iteración')
plt.ylabel('Pérdida')
plt.show()

### **DESCENSO DE GRADIENTE:**

El **descenso de gradiente** es un algoritmo de optimización ampliamente utilizado en el campo del aprendizaje automático y en la resolución numérica de problemas de optimización.

Su objetivo principal es encontrar el **mínimo de una función**, lo que es esencial en la optimización de modelos y la resolución de problemas matemáticos, para ajustar los parámetros de manera que la **función de costo se minimice**.

El descenso de gradiente tiene la forma:

\begin{equation} (ϴ_0, ϴ_1)_{i+1} = (ϴ_0, ϴ_1)_i - α * \frac{∂\,\,c(ϴ_0, ϴ_1)}{∂(ϴ_0, ϴ_1)} \, \, \,\, \, \,\, \, \, ; \, \, \,\, \, \,\, \, \, α \in (0, 1) \end{equation}

Donde su predicción:

\begin{equation} h_ϴ(x) = ϴ_1x + ϴ_0  \, \, \, \equiv \, \, \, y = mx + b \end{equation}

In [ ]:
# Definir parámetros
tamaño_paso = 0.001
theta_0 = 0
theta_1 = 0

perdida = []

La función de costo tiene la forma:

\begin{equation} c(ϴ_0, ϴ_1) = \frac{1}{n} Σ_{i=1}^n(h_ϴ(x_i) - y_i)² \end{equation}

Al derivar función de costo:

*   Parámetro 1:

\begin{equation} \frac{∂}{∂(ϴ_0)}\ c(ϴ_0, ϴ_1) =  \frac{2}{n} Σ_{i=1}^n(h_ϴ(x_i) - y_i) \end{equation}


*   Paramétro 2:

\begin{equation} \frac{∂}{∂(ϴ_1)}\ c(ϴ_0, ϴ_1) =  \frac{2}{n} Σ_{i=1}^n(h_ϴ(x_i) - y_i)(x_i) \end{equation}

In [ ]:
# Realizar algoritmo del descenso de gradiente
num_iteraciones = 100

for i in range(num_iteraciones):
    y_pred = theta_1 * x + theta_0
    error = ((y_pred - y) ** 2).mean()
    perdida.append(error)

    d_theta_0 = (2 / len(x)) * np.sum(y_pred - y)
    d_theta_1 = (2 / len(x)) * np.sum((y_pred - y) * x)

    theta_0 = theta_0 - tamaño_paso * d_theta_0
    theta_1 = theta_1 - tamaño_paso * d_theta_1

print(f'y = {theta_1} x + {theta_0}')

In [ ]:
# Visualizar la regresión lineal por descenso de gradiente
plt.plot(x, y, 'o', color = 'lightgray', label = 'Datos')
plt.plot(x, theta_1 * x + theta_0, color = 'red', label = 'Descenso de gradiente')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.legend()
plt.grid()
plt.show()

In [ ]:
# Predicción de valores con descenso de gradiente
tb_pred_gd = int(input('Agrega el valor del total de la cuenta que deseas predecir la propina: '))
y_pred_gd = round(theta_1 * tb_pred_gd + theta_0, 2)

print(f'La propina será de {y_pred_gd}')

In [ ]:
# Visualizar las pérdidas
plt.plot(perdida)
plt.xlabel('Iteración')
plt.ylabel('Pérdida')
plt.show()

In [ ]:
# Comparar las rectas obtenidas por los algoritmos
plt.plot(x, y, 'o', color = 'lightgray', label = 'Datos')
plt.plot(x, beta*x + alpha, color = 'blue', label = 'Regresión lineal')
plt.plot(x, theta_1 * x + theta_0, color = 'red', label = 'Descenso de gradiente')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.legend()
plt.grid()
plt.show()

## **CHALLENGE: ANÁLISIS PREDICTIVO DE DATOS**

Una vez visto el ***Hands - On: Introducción a la estadística inferencial***, se presentan las siguientes actividades para que el alumnado pueda repasar y reforzar lo aprendido dentro de la clase.

Dentro de la siguiente dinámica, **se realizará un análisis de estadística inferecial** haciendo uso de **operaciones vectorizadas y visualización de datos** a través del **dataset taxis** proveniente de la librería de ***Seaborn***.

Donde los análisis a realizar son:

*   **Prueba de hipótesis**
*   **Aprendizaje estadístico**

**IMPORTANTE:** Para su revisión, **es indispensable que los apartados anteriores se encuentren llenados con el código visto durante la sesión.**

### **INSTRUCCIONES:**

**1. Importa las librerías:** Carga las bibliotecas de Numpy, Pandas, Seaborn y Matplotlib.pyplot.

In [ ]:
# Importar librerías
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

**2. Importa el dataset de taxis:** Crea una variable denominada df_taxis donde se importe el dataset taxis.

In [ ]:
# Importar dataset
df= sns.load_dataset('taxis')
df

**3. Realiza una prueba de hipótesis:** Determina si existe una diferencia significativa entre la distancia recorrida de los taxis color amarillo y verde.

Donde:

   * H0: La media de distancia es igual para ambos colores.
   * H1: La media de distancia es distinta entre colores.

In [ ]:
df.info()

In [ ]:
# Importar módulo
from scipy import stats

In [ ]:
# Separación de grupos
taxis_amarillo = df[df['color']== 'yellow']
taxis_verde = df[df['color']== 'green']

distancia_amarillo = taxis_amarillo['distance']
distancia_verde = taxis_verde['distance']

In [ ]:
# Aplicar Prueba T de Student

t_stats2, p_value2 = stats.ttest_ind(distancia_amarillo, distancia_verde)

print(f"Estadístico T: {t_stats2:.4f}")
print(f"P-Value: {p_value2:.4f}")

In [ ]:
# Interpretación automática
if p_value2 < 0.01:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia muy significativa entre las propinas de ambos grupos.")
elif p_value2 >= 0.01 and p_value2 < 0.05:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia altamente significativa entre las propinas de ambos grupos.")
elif p_value2 >= 0.05 and p_value2 < 0.10:
    print("\nConclusión: Rechazamos la Hipótesis Nula.")
    print("Existe una diferencia moderadamente significativa entre las propinas de ambos grupos.")
else:
    print("\nConclusión: No podemos rechazar la Hipótesis Nula.")
    print("No hay evidencia suficiente para decir que las propinas son diferentes.")

**4. Realiza un aprendizaje estadístico:**

   * Crea un modelo de regresión lineal simple para predecir el costo del viaje en función de la distancia recorrida.
   * Ajusta el modelo a través del algoritmo de optimización del descenso de gradiente.
   * Utiliza el modelo ajustado para realizar una predicción de cuánto costará un viaje de dado un valor agregado por el usuario en unidades de distancia.

Utilizare la columna total ya que tiene en mente todo el recorrido.

In [ ]:
# Definir regresión lineal

x2= df['distance']
y2= df['total']

linear_regression2 = np.polyfit(x2,y2,1)
beta2, alpha2 = linear_regression2

print(f'y= {beta2:.3f}x + {alpha2:.3f}')

In [ ]:
# Realizar algoritmo del descenso de gradiente

m = 0
b = 0

# Hiperparámetros
learning_rate = 0.001
num_iteraciones2 = 100

# Historial del costo
cost_history = []

for i in range(num_iteraciones2):

    # Predicción
    y_pred2 = m * x2 + b

    # Error
    error = ((y_pred2 - y2) ** 2).mean()
    cost_history.append(error)

    # Gradientes
    db = (2/ len(x2)) * np.sum(y_pred2 - y2)
    dm = (2/ len(x2)) * np.sum((y_pred2 - y2) * x2)

    # Actualización de parámetros
    m = m - learning_rate * dm
    b = b - learning_rate * db


# Resultados
print(f"Pendiente (m): {m:.4f}")
print(f"Intercepto (b): {b:.4f}")

In [ ]:
# Predicción de valores con descenso de gradiente

distancia_usuario = float(input("Ingresa la distancia del viaje: "))

prediccion = m * distancia_usuario + b

print(f"El costo estimado del viaje es: {prediccion:.2f}")

**5. Visualiza los resultados:**

   * Grafica las líneas de las regresiones para comparar entre la regresión lineal simple y el algoritmo de optimización.
   * Grafica la función de costo resultante del ajuste con el algoritmo de optimización.

In [ ]:
plt.plot(x2,y2,'o', color = 'lightgray', label = 'Datos')
plt.plot(x2, beta2*x2 + alpha2, color = 'blue', label = 'Regresión lineal')
plt.plot(x2, m*x2 + b, color = 'red', label = 'Descenso de gradiente')
plt.xlabel('Distancia')
plt.ylabel('Pago Total')
plt.title("Comparación de métodos")
plt.legend()
plt.grid()
plt.show()

In [ ]:
# Visualizar función de costo

plt.figure(figsize=(8,5))

plt.plot(cost_history)

plt.xlabel('Iteraciones')
plt.ylabel('Costo')
plt.title('Evolución de la Función de Costo')

plt.show()